spring:
  autoconfigure:
    exclude:
      - 'org.springframework.cloud.vault.config.VaultAutoConfiguration'
      - 'org.springframework.cloud.vault.config.VaultObservationAutoConfiguration'
      - 'org.springframework.cloud.vault.config.VaultReactiveAutoConfiguration'

grpc:
  client:
    grpcCurrencyClient:
      address: 'static://127.0.0.1:8092'
      negotiationType: PLAINTEXT

rococo-userdata:
  base-uri: 'http://127.0.0.1:8089'
rococo-front:
  base-uri: 'http://127.0.0.1:3000'
rococo-gateway:
  base-uri: 'http://127.0.0.1:8090'